name: pyright
on: [push]
jobs:
  pyright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install pipenv && pipenv sync --dev
      - run: pipenv run pyright
      - uses: jakebailey/pyright-action@v1
      - run: echo "🍏 This job's status is ${{ job.status }}."